export const mutationTypes = {
  SET_MENU_MOBILE_OPEN: 'SET_MENU_MOBILE_OPEN',

  SET_CLIENT_LOGOS: 'SET_CLIENT_LOGOS',

  SET_ANIMATION_SHOWN: 'SET_ANIMATION_SHOWN',

  SET_SLIDE_COLOR: 'SET_SLIDE_COLOR',
  SET_SLIDE_TONE: 'SET_SLIDE_TONE',
  SET_SLIDE_CONFIG: 'SET_SLIDE_CONFIG'
}
